# -*- coding: utf-8 -*-
"""DataColletion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDWuJUQYXMtOrwYQfN7vqQJ7p_lVUFqr

Websites for Collecting Data:
1. kaggle
2. UCI ML repositories
3. google dataset search
"""

import pandas as pd

ds = pd.read_csv('/content/housing.csv')

ds.head()

!pip install kaggle

# configuring the path of kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""importing the earthquake dataset"""

!kaggle competitions download -c LANL-Earthquake-Prediction
# API to fetch the dataset from kaggle

from zipfile import ZipFile
dataset = '/content/LANL-Earthquake-Prediction.zip'
with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('dataset is extracted')

