set1={1,2,3}
set2={3,4,5}
union_set=set1.union(set2)
intersection_set=set1.intersection(set2)
diff_set=set1.difference(set2)
symm_set=set1.symmetric_difference(set2)
print(union_set)
print(intersection_set)
print(diff_set)
print(symm_set)
