# -*- coding: utf-8 -*-
"""LabelEncoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-THxQyT6GIrX7Fl9Zd7F1AgCdgXk85v

label encoding:
<br>
converting the labels into numeric form
"""

# importing the dependencies
import pandas as pd
from sklearn.preprocessing import LabelEncoder

"""label encoding breast cancer dataset"""

# loading data from csv file to pandas dataframe
cancer_data = pd.read_csv('/content/data.csv')

cancer_data.head()

# finding the count of different labels in a column
cancer_data['diagnosis'].value_counts()

# load the label encoder function
label_encode = LabelEncoder()

label = label_encode.fit_transform(cancer_data.diagnosis)

cancer_data['target']  = label
# appending the labels to the dataframe

cancer_data.head()

"""B --> benign
M --> malignant
"""

cancer_data['target'].value_counts()

"""label encoding the iris dataset"""

iris_data = pd.read_csv('/content/iris_data.csv')

iris_data.head()

iris_data['Species'].value_counts()

label2 = label_encode.fit_transform(iris_data.Species)

iris_data['target'] = label2

iris_data.head()

iris_data['target'].value_counts()

"""iris-setosa --> 0 <br>
iris-versicolor --> 1<br>
iris-virginica -->2
"""

