# -*- coding: utf-8 -*-
"""numpybasics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjoxFEBXEx4iuzM2CgdHnq7ppOvEGTBZ
"""

import numpy as np

# list vs numpy array -> time taken to perform task
from time import process_time

python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()
print(end_time - start_time)

np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array+=5
end_time = process_time()
print(end_time - start_time)

list1 = [1,2,3,4,5]
print(list1)
type(list1)

np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

b.shape

c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)

print(c)

x = np.zeros((4,5))
print(x)

y = np.ones((5,4))
print(y)

z = np.full((6,3),8)
print(z)

# create an identity matrix
a = np.eye(5)
print(a)

# create an array with random values between 0 and 1
b = np.random.random((2,3))
print(b)

# create an array with random integers
c = np.random.randint(10,100,(4,5))
print(c)

# create an array of evenly spaced values --> specifying the no of values required in the range
d = np.linspace(10,30,5)
print(d)

e = np.linspace(20,50,7)
print(e)

# create an array of evenly spaced values --> specifying the step
f = np.arange(10,30,5)
print(f)

#converting a list to a numpy array
list1 = [1,2,3,4,5]
np_array = np.asarray(list1)
print(np_array)
type(np_array)

# converting tuple into a numpy array
t1 = (1,2,3,4,5)
na = np.asarray(t1)
print(na)
type(na)

"""Analyzing a numpy array"""

c = np.random.randint(10,90,(5,5))
print(c)

# dimensions of array
print(c.shape)

# number of dimensions
print(c.ndim)

# number of elements in the array
print(c.size)

# checking the data type of the values in the array
print(c.dtype)

"""Mathematical operations on numpy array"""

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

print(a+b)

print(a-b)
print(a*b)
print(a/b)

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

a = np.random.randint(19,59,(2,3))
print(a)
print(a.shape)

t = np.transpose(a)
print(t)
print(t.shape)

t2 = a.T
print(t2)
print(t2.shape)

a= np.random.randint(0,10,(2,3))

print(a)
print(a.shape)

b = a.reshape(3,2)

print(b)
print(b.shape)

