# -*- coding: utf-8 -*-
"""seabornBasics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vX9LZHvw-XerrTP2BKdIDrTCVLtZ7fxX

seaborn :
1. Data visualization libary
"""

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

"""Note :- Seaborn have some built-in libraries"""

tips = sns.load_dataset('tips')

tips.head()

sns.set_theme()

sns.relplot(data=tips, x='total_bill',y='tip',col='time',hue='smoker',style='smoker',size='size')

iris = sns.load_dataset('iris')

iris.head()

"""Scatter Plot"""

sns.scatterplot(x='sepal_length',y='petal_length',hue='species',data=iris)

sns.scatterplot(x='sepal_length',y='petal_width',hue='species',data=iris)

titanic=sns.load_dataset('titanic')

titanic.head()

"""Count Plot"""

sns.countplot(x='class',data=titanic)

titanic.shape

sns.countplot(x='survived',data=titanic)

"""Bar Plot"""

sns.barplot(x='sex',y='survived',hue='class',data=titanic)

from sklearn.datasets import fetch_california_housing
house_cal=fetch_california_housing()
house=pd.DataFrame(house_cal.data,columns=house_cal.feature_names)
house['PRICE']=house_cal.target

house.head()

print(house_cal)

"""Distribution Plot"""

sns.displot(house['PRICE'])

sns.distplot(house['PRICE'])

"""CORREALTION:
1. positive correlation
2. negative correlation

Heat Map
"""

correlation = house.corr()

#constructing a heat map
plt.figure(figsize=(10,10))
sns.heatmap(correlation, cbar=True, square= True, annot= True,fmt='.1f', annot_kws={'size':8}, cmap='Blues')
# dark blue is positive correlation and light blue is negative correlation

